config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    resources :questions

    resources :tests do
      resources :attempts
      collection do
        post :import
      end
    end

    resources :answers, only: [], param: :index do
      member do
        delete "(:id)", to: "answers#destroy", as: ""
        post "/" => "answers#create"
      end
    end
    resources :categories, only: [], param: :index do
      member do
        delete "(:id)", to: "categories#destroy", as: ""
        post "/" => "categories#create"
      end
    end

    devise_for :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get ":locale", to: "pages#home", as: :root_with_locale
  root "pages#home"
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :attempts_questions, dependent: :delete_all
  has_many :user_tests, through: :attempts_questions
  has_and_belongs_to_many :tests
  has_and_belongs_to_many :categories
  has_many :translations, as: :translatable
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true

  validates :assignment, presence: true
  validates :is_multichoice, inclusion: { in: [ true, false ] }
  validate :must_have_at_least_one_answer

  private

  def must_have_at_least_one_answer
    actual_answers = answers.reject { |a| a.marked_for_destruction? || a.body.blank? }

    if actual_answers.empty?
      errors.add(:answers, :one_answer)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.answers.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_url, status: :see_other, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:assignment, :is_multichoice,
                                       answers_attributes: [ :id, :body, :is_correct, :_destroy ],
                                       categories_attributes: [ :id, :title, :_destroy ],
                                       category_ids: [])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= t("helpers.error.header", count: @question.errors.count, model: t("activerecord.models.question")) %></h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :assignment, class: 'form-label' %>
    <%= form.text_area :assignment, class: 'form-control'%>
  </div>

  <div class="form-check form-switch">
    <%= form.check_box :is_multichoice, class: 'form-check-input' %>
    <%= form.label :is_multichoice, class: 'form-check-label' %>
  </div>

  <div id="answers">
    <%= form.fields_for :answers do |af| %>
      <%= render "answers/form", form: af %>
    <% end %>
  </div>

  <%= form.submit "Add answer", class: 'btn btn-outline-primary',
                  formaction: answer_path(@question.answers.size),
                  formmethod: :post,
                  formnovalidate: true,
                  id: "add-answer"
  %>

  <hr>

  <%= form.label :categories, "Categories" %><br>
  <div class="d-flex my-1 align-items-center flex-wrap">
    <% Category.all.each do |category| %>
      <div class="me-1">
        <%= check_box_tag "question[category_ids][]", category.id, @question.category_ids.include?(category.id), id: "category_#{category.id}", class: 'd-none category-checkbox' %>
        <%= label_tag "category_#{category.id}", category.title, class: "btn btn-outline-primary toggle-label" %>
      </div>
    <% end %>
    <div id="categories" class="d-flex flex-wrap">
      <%= form.fields_for :categories do |cf| %>
        <% unless form.object.persisted? %>
          <%= render "categories/form", form: cf %>
        <% end %>
      <% end %>
    </div>
    <%= form.submit "add category", class: 'btn btn-outline-secondary',
                    formaction: category_path(@question.categories.size),
                    formmethod: :post,
                    formnovalidate: true,
                    id: "add-category"
    %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-outline-success mt-4' %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <% user_answers = @attempt&.attempts_questions&.index_by(&:question_id) || {} %>
  <div class="border border-black rounded p-2 mb-4 shadow hover-shadow">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h3 class="text-wrap text-break me-3 flex-3">
        <%= question.assignment %>
      </h3>
      <div class="d-flex gap-2 flex-wrap flex-1 justify-content-end">
        <% question.categories.each do |q| %>
          <span class="border border-primary rounded-1 bg-primary-subtle mx-1 px-2 py-1">
            <%= q.title %>
          </span>
        <% end %>
      </div>
    </div>
    <div class="row">
      <% question.answers.each do |a| %>
        <div class="col-12 col-md-6 mb-2">
          <% selected_answer_id = user_answers[question.id]&.answer_id %>
          <% answer_classes =
               if @attempt && selected_answer_id == a.id && !a.is_correct
                 "bg-danger bg-opacity-25 border-danger"
               elsif a.is_correct
                 "bg-success bg-opacity-25 border-success"
               else
                 "border-black"
               end
          %>

          <div class="border rounded p-2 h-100 <%= answer_classes %>">
            <%= a.body %><br>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render "shared/link_back", path: question_path(@question), text: "<-- question" %>
<h1>Editing question</h1>

<%= render "form", question: @question %>

app/views/questions/index.html.erb
<% content_for :title, "Questions" %>

<div class="d-flex justify-content-between align-items-center w-100">
  <h1><%= t(".header") %></h1>
  <%= link_to new_question_path, class: 'btn btn-primary' do %>
    <i class="bi bi-plus-lg me-2"></i><%= t(".new") %>
  <% end %>
</div>

<div id="questions">
  <% @questions.each do |question| %>
    <%= link_to question, class: "text-decoration-none text-black" do %>
      <%= render question %>
    <% end %>
  <% end %>
</div>

app/views/questions/new.html.erb
<%= render "shared/link_back", path: questions_path, text: "<-- questions" %>
<h1><%= t(".header") %>></h1>

<%= render "form", question: @question %>

app/views/questions/show.html.erb
<%= render "shared/link_back", path: questions_path, text: "<-- #{t(".back")}" %>
<%= render @question %>

<div class="d-flex justify-content-between align-items-center">
  <%= link_to t(".edit"), edit_question_path(@question), class: 'btn btn-outline-primary' %>
  <%= button_to t(".destroy"), @question, method: :delete, class: 'btn btn-outline-danger'%>
</div>