config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    resources :questions

    resources :tests do
      resources :attempts
      collection do
        post :import
      end
    end

    resources :answers, only: [], param: :index do
      member do
        delete "(:id)", to: "answers#destroy", as: ""
        post "/" => "answers#create"
      end
    end
    resources :categories, only: [], param: :index do
      member do
        delete "(:id)", to: "categories#destroy", as: ""
        post "/" => "categories#create"
      end
    end

    devise_for :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get ":locale", to: "pages#home", as: :root_with_locale
  root "pages#home"
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :test
  has_many :attempts_questions, dependent: :delete_all
  has_many :questions, through: :attempts_questions
  accepts_nested_attributes_for :attempts_questions
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attempt, only: %i[ destroy edit update ]
  before_action :set_test

  # GET /user_tests or /user_tests.json
  def index
    @attempts = current_user.attempts.includes(:questions).where(test_id: params[:test_id])
  end

  # GET /user_tests/1 or /user_tests/1.json
  def show
    @attempt = Attempt.includes(:attempts_questions).find(params[:id])
  end

  def edit
    @test.questions.each do |question|
      unless @attempt.attempts_questions.any? { |aq| aq.question_id == question.id }
        @attempt.attempts_questions.build(question: question)
      end
    end
  end

  # GET /user_tests/new
  def new
    @attempt = current_user.attempts.build(test: @test)

    @test.questions.each do |question|
      @attempt.attempts_questions.build(question: question)
    end
  end

  # POST /user_tests or /user_tests.json
  def create
    @attempt = current_user.attempts.build(attempt_params.merge(test_id: params[:test_id]))

    if @attempt.save
      evaluate(@attempt)
      redirect_to test_attempts_url, notice: "Attempt created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @attempt.update(attempt_params.merge(test_id: params[:test_id]))
      redirect_to test_attempt_url(@test, @attempt), notice: "Attempt updated."
    else
      @test.questions.each do |question|
        unless @attempt.attempts_questions.any? { |aq| aq.question_id == question.id }
          @attempt.attempts_questions.build(question: question)
        end
      end
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /user_tests/1 or /user_tests/1.json
  def destroy
    @attempt.destroy!

    respond_to do |format|
      format.html { redirect_to test_attempts_url, status: :see_other, notice: "User test was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt
      @attempt = Attempt.find(params[:id])
    end

    def set_test
      @test = Test.find(params[:test_id])
    end

    def attempt_params
      params.require(:attempt).permit(:country, :city, :score,
                                      attempts_questions_attributes: [ :id, :written_answer, :answer_id, :time, :question_id ])
    end

  def evaluate(attempt)
    points = 0

    attempt.attempts_questions.includes(:answer).each do |aq|
      if aq.answer&.is_correct
        points += 1
      end
    end

    attempt.update(score: points)
  end
end

app/views/attempts/_attempt.html.erb
<div id="<%= dom_id attempt %>">
  <div class="border border-black rounded p-1 mb-1 d-flex justify-content-between">
    <div>score: <%= attempt.score %> / <%= attempt.questions.size %></div>
    <div>city: <%= attempt.city %></div>
    <div>country: <%= attempt.country %></div>
    <div>time: <%= attempt.time %></div>
  </div>
</div>

app/views/attempts/_form.html.erb
<%= form_with(model: attempt, url: attempt.persisted? ? test_attempt_path(@test, attempt) : test_attempts_path) do |form| %>
  <% if @attempt.errors.any? %>
    <div style="color: red">
      <h2><%= t("helpers.error.header", count: @attempt.errors.count, model: t("activerecord.models.attempt")) %></h2>
      <ul>
        <% @attempt.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :country, class: 'form-label' %>
    <%= form.text_field :country, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :city, class: 'form-label' %>
    <%= form.text_field :city, class: 'form-control' %>
  </div>

  <% if form.object.persisted? %>
    <div>
      <%= form.label :score, class: 'form-label' %>
      <%= form.number_field :score, class: 'form-control' %>
    </div>
  <% else %>
    <%= form.fields_for :attempts_questions do |aq_form| %>
      <% question = aq_form.object.question %>

      <div>
        <h4><%= question.assignment %></h4>
        <div class="row">
          <% question.answers.each do |answer| %>
            <div class="col-12 col-md-6 mb-2">
              <%= aq_form.radio_button :answer_id, answer.id, id: "question_#{question.id}_answer_#{answer.id}", class: 'd-none category-checkbox' %>
              <%= label_tag "question_#{question.id}_answer_#{answer.id}", class: "btn btn-outline-primary w-100 toggle-label text-wrap text-start" do %>
                <%= answer.body %>
              <% end %>
            </div>
          <% end %>
        </div>

        <%= aq_form.hidden_field :question_id %>
      </div>
    <% end %>
  <% end %>
  <div>
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/attempts/edit.html.erb
<%= render "shared/link_back", path: test_attempts_path, text: "<-- attempts" %>
<h1>Editing attempt <%= @attempt.id %> of test <%= @test.id %></h1>

<%= render "form", attempt: @attempt, test: @test %>

app/views/attempts/index.html.erb
<%= render "shared/link_back", path: tests_path, text: "<-- #{t(".back")}" %>
<div class="d-flex justify-content-between align-items-center w-100">
  <h1><%= t(".header") %></h1>
  <%= link_to new_test_attempt_path, class: 'btn btn-primary' do %>
    <i class="bi bi-plus-lg me-2"></i><%= t(".new") %>
  <% end %>
</div>

<div id="attempt">
  <% @attempts.each do |attempt| %>
    <%= link_to test_attempt_path(@test, attempt), class: 'text-decoration-none text-black' do %>
      <%= render attempt %>
    <% end %>
  <% end %>
</div>

app/views/attempts/new.html.erb
<% content_for :title, "New attempt" %>

<h1><%= t(".new") %> "<%= @test.title %>"</h1>
<%= render "form", attempt: @attempt, test: @test %>

app/views/attempts/show.html.erb
<%= render "shared/link_back", path: test_attempts_path, text: "<-- #{t(".back")}" %>
<%= render @attempt %>
<br>
<%= render @test %>

<% if current_user.admin? %>
  <div class="d-flex justify-content-between">
    <%= link_to t(".edit"), edit_test_attempt_path(@test, @attempt), class: 'btn btn-outline-primary' %>
    <%= button_to t(".destroy"), test_attempt_path(@test, @attempt), method: :delete, class: 'btn btn-outline-danger' %>
  </div>
<% end %>